# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68e61e3bd241795798d39028e5e4371ca562afa73686b422dcc2589d21f73719ed009ad5279e93e9e254054e750971fbf664577efdc690a44d1279ef954800eb

test:
  secret_key_base: 711ef66cb6aa2877768f8a716355eb29c379dc9a155effe721d38531dc2c39c6771101694de520453aa665bfd5bcfd89eda93293d89a863fb2c4488161e4fa03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
